name: Code Check linux/mips64le

on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string

env:
  GOOS: linux
  GOARCH: mips64le
  PLATFORM: linux/mips64le

jobs:
  linux-mips64le:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-22.04
          - ubuntu-24.04
        target:
          - image: mips64le/debian:latest
            name: CGO_ENABLED=0
            cgo: 0
          - image: mips64le/debian:latest
            name: GNU C Library
            cgo: 1
    name: linux/mips64le ${{ matrix.target.name }}(${{ matrix.target.image }})(${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/cache/restore@v6
        with:
          path: ${{ github.workspace }}/tmp/go
          key: go${{ inputs.go_version }}.${{ env.GOOS }}-${{ env.GOARCH }}
          fail-on-cache-miss: true
      - uses: docker/setup-qemu-action@v4
        with:
          platforms: ${{ env.PLATFORM }}
      - run: |
          docker run \
            --rm \
            -v $(pwd):/workspace \
            -w /workspace \
            --platform ${{ env.PLATFORM }} \
            ${{ matrix.target.image }} \
            sh -c "
              export PATH=$PATH:/workspace/tmp/go/bin &&
              export CGO_ENABLED=${{ matrix.target.cgo }} &&
              go vet ./... &&
              go test ./...
            "
