name: Code Check freebsd/amd64

on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string
      os_version:
        required: true
        type: string

env:
  GOOS: freebsd
  GOARCH: amd64
  VM_OS: freebsd
  VM_ARCHITECTURE: x86-64

jobs:
  freebsd-amd64:
    name: freebsd/amd64(FreeBSD ${{ inputs.os_version }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - id: cache
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/tmp/go
          key: go${{ inputs.go_version }}.${{ env.GOOS }}-${{ env.GOARCH }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir tmp
          cd tmp
          curl --location --output go${{ inputs.go_version }}.${{ env.GOOS }}-${{ env.GOARCH }}.tar.gz https://go.dev/dl/go${{ inputs.go_version }}.${{ env.GOOS }}-${{ env.GOARCH }}.tar.gz
          tar -xzf go${{ inputs.go_version }}.${{ env.GOOS }}-${{ env.GOARCH }}.tar.gz
          rm go${{ inputs.go_version }}.${{ env.GOOS }}-${{ env.GOARCH }}.tar.gz
      - uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: ${{ env.VM_OS }}
          version: ${{ inputs.os_version }}
          architecture: ${{ env.VM_ARCHITECTURE }}
          cpu_count: 1
          sync_files: runner-to-vm
          shell: bash
          run: |
            mv ${{ github.workspace }}/tmp/go /tmp/go
            export PATH=$PATH:/tmp/go/bin
            pkgs=$(go list -f '{{ .ImportPath }}' ./...)
            for pkg in ${pkgs}; do
              go vet ${pkg}
            done
            GOMAXPROCS=1 go test -p 1 -parallel 1 ./...
