name: Code Check netbsd/amd64

on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string
      os_version:
        required: true
        type: string

env:
  GOOS: netbsd
  GOARCH: amd64
  VM_OS: netbsd
  VM_ARCHITECTURE: x86-64

jobs:
  netbsd-amd64:
    name: netbsd/amd64(NetBSD ${{ inputs.os_version }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/cache/restore@v6
        with:
          path: ${{ github.workspace }}/tmp/go
          key: go${{ inputs.go_version }}.${{ env.GOOS }}-${{ env.GOARCH }}
          fail-on-cache-miss: true
      - uses: cross-platform-actions/action@v1.3.0
        with:
          operating_system: ${{ env.VM_OS }}
          version: ${{ inputs.os_version }}
          architecture: ${{ env.VM_ARCHITECTURE }}
          cpu_count: 1
          sync_files: runner-to-vm
          shell: bash
      - shell: cpa.sh {0}
        run: |
          export PATH=$PATH:${{ github.workspace }}/tmp/go/bin
          pkgs=$(go list -f "{{ .ImportPath }}" ./...)
          for pkg in ${pkgs}; do
            go vet ${pkg}
          done
          GOMAXPROCS=1 go test -p 1 -parallel 1 ./...
