name: Create Cache 1.23

on:
  workflow_call:

env:
  GO_VERSION: 1.23.12

jobs:
  create-cache-darwin:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
    name: Create Cache macOS(${{ matrix.target.os }}/${{ matrix.target.arch }})
    runs-on: macos-latest
    steps:
      - id: cache
        uses: actions/cache/restore@v6
        with:
          path: ${{ github.workspace }}/tmp/go
          key: go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}
          lookup-only: true
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl --location --create-dirs --output tmp/go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.gz https://go.dev/dl/go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.gz
          tar -xzf tmp/go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.gz --directory=tmp --exclude='go/api' --exclude='go/doc' --exclude='go/misc' --exclude='go/src/*_test.go' --exclude='go/test'
      - if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v6
        with:
          path: ${{ github.workspace }}/tmp/go
          key: go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}

  create-cache-linux:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: dragonfly
            arch: amd64
          - os: freebsd
            arch: amd64
          - os: freebsd
            arch: arm64
          - os: linux
            arch: '386'
          - os: linux
            arch: 'amd64'
          - os: linux
            arch: arm64
          - os: linux
            arch: armv6l
          # - os: linux
          #   arch: mips64le
          - os: linux
            arch: ppc64le
          - os: linux
            arch: riscv64
          - os: linux
            arch: s390x
          - os: netbsd
            arch: amd64
          - os: netbsd
            arch: arm64
          - os: openbsd
            arch: amd64
          - os: openbsd
            arch: arm64
    name: Create Cache Linux(${{ matrix.target.os }}/${{ matrix.target.arch }})
    runs-on: ubuntu-latest
    steps:
      - id: cache
        uses: actions/cache/restore@v6
        with:
          path: ${{ github.workspace }}/tmp/go
          key: go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}
          lookup-only: true
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl --location --create-dirs --output tmp/go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.gz https://go.dev/dl/go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.gz
          tar -xzf tmp/go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.gz --directory=tmp --exclude='go/api' --exclude='go/doc' --exclude='go/misc' --exclude='go/src/*_test.go' --exclude='go/test'
      - if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v6
        with:
          path: ${{ github.workspace }}/tmp/go
          key: go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}

  create-cache-windows:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: windows
            arch: '386'
          - os: windows
            arch: 'amd64'
          - os: windows
            arch: 'arm64'
    name: ${{ matrix.target.os }}/${{ matrix.target.arch }}
    runs-on: windows-latest
    steps:
      - id: cache
        uses: actions/cache/restore@v6
        with:
          path: ${{ github.workspace }}/tmp/go
          key: go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}
          lookup-only: true
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          New-Item -ItemType Directory -Path "tmp"
          Invoke-WebRequest -Uri "https://go.dev/dl/go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}.zip" -OutFile "tmp/go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}.zip"
          Expand-Archive -Path "tmp/go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}.zip" -DestinationPath "tmp"
          Remove-Item -Recurse "tmp/go/api"
          Remove-Item -Recurse "tmp/go/doc"
          Remove-Item -Recurse "tmp/go/misc"
          Remove-Item -Recurse "tmp/go/test"
          Get-ChildItem -Path "tmp/go/src" -Filter "*_test.go" -Recurse | Remove-Item
      - if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v6
        with:
          path: ${{ github.workspace }}/tmp/go
          key: go${{ env.GO_VERSION }}.${{ matrix.target.os }}-${{ matrix.target.arch }}
