name: Create Cache

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  create-cache-1_22:
    name: Go 1.22
    uses: ./.github/workflows/create-cache-1.22.yml

  create-cache-1_23:
    name: Go 1.23
    uses: ./.github/workflows/create-cache-1.23.yml

  create-cache-1_24:
    name: Go 1.24
    uses: ./.github/workflows/create-cache-1.24.yml

  create-cache-1_25:
    name: Go 1.25
    uses: ./.github/workflows/create-cache-1.25.yml
