name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag format is Semver
        required: true

jobs:
  code-check:
    uses: ./.github/workflows/code-check.yml

  release:
    needs:
      - code-check
    if: ${{ github.event.inputs.tag }} =~ ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)
    runs-on: ubuntu-latest
    steps:
      - name: release
        run: |
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}
